#!/bin/python

from os import system

files = {
    "~/bin/*": "./bin/",
    "~/.zshrc": "./zshrc",
    "~/.xinitrc": "./xinitrc",
    "~/.vim/*": "./vim/*",
    "~/.gitconfig": "./gitconfig",
    "~/.tmux.conf": "./tmux.conf",
}


def get_keys(dictionary):
    return [key for key in dictionary.keys()]


def get_values(dictionary):
    return [val for val in dictionary.values()]


def update_files(list_of_files, list_of_destination):
    for i in range(len(list_of_files)):
        print(f"Copying {list_of_files[i]} on {list_of_destination[i]} \n")
        system(f"cp -r {list_of_files[i]} {list_of_destination[i]}")
    print("Done! \n")


def update_git():
    system(f"git add . && git commit -m '🚀 Update'")
    system("git push")


if __name__ == "__main__":
    update_files(get_keys(files), get_values(files))
    update_git()
