#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 3 5 7

SCS=$HOME/scripts/activate_second_monitor.sh

if test -f "$SCS";then
	source $SCS
	bspc monitor HDMI1 -d 2 4 6 8
	polybar top_external &
fi

$HOME/.config/polybar/launch.sh &

bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       5
bspc config window_gap         16

bspc config active_border_color '#87CEEB'
bspc config normal_border_color '#087CEEB'
bspc config focused_border_color '#87CEEBC'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# More Stuff
picom -b -f
feh --bg-fill ~/Disk/Sabare/Wallpapers/cool.jpg
