#!/bin/python

import os

principal_monitor = os.popen("xrandr --query | grep primary").read().split()[0]

class Monitor():
    def __init__(self, monitor_name, side):
        self.monitor_name = monitor_name
        self.side = side

    def is_conected(self):
        return "connected" in os.popen(f"xrandr --query | grep {self.monitor_name}").read()

    def activate(self):
        os.system(f" xrandr --output {self.monitor_name} --auto --{self.side}-of {principal_monitor}")

if __name__ == "__name__":
    # My Second Display
    my_second_monitor = Monitor("HDMI1","rigth")
    if my_second_monitor.is_conected():
        my_second_monitor.activate()
