#!/usr/bin/env node

const { copyFile } = require("fs");
const { exec } = require("child_process");
const { resolve } = require("path");

const FILES = {
  "~/bin/": "./bin/",
  "~/.zshrc": "./zshrc",
  "~/.xinitrc": "./xinitrc",
  "~/.ideavimrc": "./ideavimrc.vim",
  "~/.vim/vimrc": "./vimrc",
  "~/.gitconfig": "./gitconfig",
  "~/.tmux.conf": "./tmux.conf",
  "~/.config/i3/": "./config/i3/",
  "~/.config/neofetch/": "./config/neofetch/",
};

function cp(fileToCopy, whereToCopy) {
  console.log(`Copying ${fileToCopy}...`);
  copyFile(fileToCopy.replace("~", process.env.HOME), whereToCopy, (err) => {
    err ? console.error(err) : console.log(`Finish copying ${fileToCopy} :)`);
  });
}

function update_files(listOfFiles, listOfDestination) {
  for (let i = 0; i < listOfDestination.length; i++) {
    cp(listOfFiles[i], listOfDestination[i]);
  }
}

function updateGit() {
  exec("git add . && git commit -m '🚀 Update' && git push");
}

function init() {
  update_files(Object.keys(FILES), Object.values(FILES));
  updateGit();
}

init();
