#!/usr/bin/env node

const { copyFile, readdir } = require("fs");
const { exec } = require("child_process");

const FILES = {
  "~/.zshrc": "./.zshrc",
  "~/.xinitrc": "./.xinitrc",
  "~/.ideavimrc": "./.ideavimrc.vim",
  "~/.vim/vimrc": "./.vimrc",
  "~/.gitconfig": "./.gitconfig",
  "~/.tmux.conf": "./.tmux.conf",
  "~/.config/i3/config": "./config/i3/config",
  "~/.config/alacritty/alacritty.yml": "./config/alacritty/alacritty.yml",
  "~/.config/efm-langserver/config.yaml": "./config/efm-langserver/config.yml",
  "~/.config/neofetch/config.conf": "./config/neofetch/config.conf",
  "~/.config/wallger/config.json": "./config/wallger/config.json",
};

function cpFIles(fileToCopy, whereToCopy) {
  console.log(`Copying ${fileToCopy}...`);
  copyFile(fileToCopy.replace("~", process.env.HOME), whereToCopy, (err) => {
    err ? console.error(err) : console.log(`Finish copying ${fileToCopy} :)`);
  });
}

function update_files(listOfFiles, listOfDestination) {
  for (let i = 0; i < listOfDestination.length; i++) {
    cpFIles(listOfFiles[i], listOfDestination[i]);
  }
}

function updateGit() {
  exec("git add . && git commit -m '🚀 Update' && git push", (err) =>
    err ? console.ererror(err) : console.log("Deployed!")
  );
}

function init() {
  update_files(Object.keys(FILES), Object.values(FILES));
  updateGit();
}

init();
